<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251023162654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Drop old tables first
        $this->addSql('DROP TABLE IF EXISTS data_point CASCADE');
        $this->addSql('DROP TABLE IF EXISTS log_session CASCADE');

        // Create new trip table
        $this->addSql('CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, file_path VARCHAR(255) DEFAULT NULL, session_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration INT DEFAULT NULL, distance NUMERIC(8, 2) DEFAULT NULL, data_points_count INT DEFAULT NULL, status VARCHAR(20) NOT NULL, analysis_results JSON DEFAULT NULL, catalyst_efficiency NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_st NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_lt NUMERIC(5, 2) DEFAULT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7656F53B545317D1 ON trip (vehicle_id)');

        // Create new trip_data table
        $this->addSql('CREATE TABLE trip_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pid_name VARCHAR(50) NOT NULL, value NUMERIC(10, 4) DEFAULT NULL, unit VARCHAR(20) DEFAULT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_86CB6008A5BC2E0E ON trip_data (trip_id)');
        $this->addSql('CREATE INDEX idx_trip_data_timestamp ON trip_data (timestamp)');
        $this->addSql('CREATE INDEX idx_trip_data_pid_name ON trip_data (pid_name)');

        // Add foreign keys
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_data ADD CONSTRAINT FK_86CB6008A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE data_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "timestamp" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pid_name VARCHAR(50) NOT NULL, value NUMERIC(10, 4) DEFAULT NULL, unit VARCHAR(20) DEFAULT NULL, log_session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f91a3fbb6b294064 ON data_point (log_session_id)');
        $this->addSql('CREATE INDEX idx_timestamp ON data_point ("timestamp")');
        $this->addSql('CREATE INDEX idx_pid_name ON data_point (pid_name)');
        $this->addSql('CREATE TABLE log_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, file_path VARCHAR(255) DEFAULT NULL, session_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration INT DEFAULT NULL, distance NUMERIC(8, 2) DEFAULT NULL, data_points_count INT DEFAULT NULL, status VARCHAR(20) NOT NULL, analysis_results JSON DEFAULT NULL, catalyst_efficiency NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_st NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_lt NUMERIC(5, 2) DEFAULT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e889ed43545317d1 ON log_session (vehicle_id)');
        $this->addSql('ALTER TABLE data_point ADD CONSTRAINT fk_f91a3fbb6b294064 FOREIGN KEY (log_session_id) REFERENCES log_session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_session ADD CONSTRAINT fk_e889ed43545317d1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B545317D1');
        $this->addSql('ALTER TABLE trip_data DROP CONSTRAINT FK_86CB6008A5BC2E0E');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE trip_data');
    }
}
