<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration complète CheckEngine - Schéma complet avec TimescaleDB
 */
final class Version20251024210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Complete CheckEngine schema with TimescaleDB hypertable and Toyota Prius+ fixture';
    }

    public function up(Schema $schema): void
    {
        // Enable TimescaleDB extension
        $this->addSql('CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE');

        // Clean slate - drop everything if exists
        $this->addSql('DROP TABLE IF EXISTS trip_diagnostic CASCADE');
        $this->addSql('DROP TABLE IF EXISTS trip_data CASCADE');
        $this->addSql('DROP TABLE IF EXISTS trip CASCADE');
        $this->addSql('DROP TABLE IF EXISTS vehicle CASCADE');
        $this->addSql('DROP TABLE IF EXISTS vehicle_model CASCADE');
        $this->addSql('DROP TABLE IF EXISTS "user" CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS trip_data_id_seq CASCADE');

        // 1. Create user table
        $this->addSql('CREATE TABLE "user" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(180) NOT NULL,
            roles JSON NOT NULL,
            password VARCHAR(255) NOT NULL,
            first_name VARCHAR(100) DEFAULT NULL,
            last_name VARCHAR(100) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');

        // 2. Create vehicle_model table
        $this->addSql('CREATE TABLE vehicle_model (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            manufacturer VARCHAR(50) NOT NULL,
            model VARCHAR(100) NOT NULL,
            year_start SMALLINT NOT NULL,
            year_end SMALLINT DEFAULT NULL,
            generation VARCHAR(50) NOT NULL,
            engine_code VARCHAR(20) NOT NULL,
            displacement NUMERIC(3, 1) NOT NULL,
            fuel_type VARCHAR(50) NOT NULL,
            horse_power SMALLINT NOT NULL,
            electric_motor_power SMALLINT DEFAULT NULL,
            is_hybrid BOOLEAN NOT NULL,
            supported_pids JSON DEFAULT NULL,
            specifications JSON DEFAULT NULL,
            PRIMARY KEY (id)
        )');

        // 3. Create vehicle table
        $this->addSql('CREATE TABLE vehicle (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            nickname VARCHAR(100) NOT NULL,
            vin VARCHAR(17) DEFAULT NULL,
            license_plate VARCHAR(20) DEFAULT NULL,
            year SMALLINT NOT NULL,
            mileage INT DEFAULT NULL,
            purchase_date DATE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            owner_id INT NOT NULL,
            model_id INT NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_1B80E4867E3C61F9 ON vehicle (owner_id)');
        $this->addSql('CREATE INDEX IDX_1B80E4867975B7E7 ON vehicle (model_id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4867E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4867975B7E7 FOREIGN KEY (model_id) REFERENCES vehicle_model (id) NOT DEFERRABLE');

        // 4. Create trip table
        $this->addSql('CREATE TABLE trip (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            filename VARCHAR(255) NOT NULL,
            file_path VARCHAR(255) DEFAULT NULL,
            session_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            duration INT DEFAULT NULL,
            distance NUMERIC(8, 2) DEFAULT NULL,
            data_points_count INT DEFAULT NULL,
            status VARCHAR(20) NOT NULL,
            analysis_results JSON DEFAULT NULL,
            catalyst_efficiency NUMERIC(5, 2) DEFAULT NULL,
            avg_fuel_trim_st NUMERIC(5, 2) DEFAULT NULL,
            avg_fuel_trim_lt NUMERIC(5, 2) DEFAULT NULL,
            uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            vehicle_id INT NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_7656F53B545317D1 ON trip (vehicle_id)');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');

        // 5. Create trip_diagnostic table
        $this->addSql('CREATE TABLE trip_diagnostic (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            category VARCHAR(50) NOT NULL,
            status VARCHAR(20) NOT NULL,
            score INT NOT NULL,
            confidence VARCHAR(20) NOT NULL,
            details JSON NOT NULL,
            messages JSON NOT NULL,
            recommendations JSON NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            trip_id INT NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_F6E539FA5BC2E0E ON trip_diagnostic (trip_id)');
        $this->addSql('ALTER TABLE trip_diagnostic ADD CONSTRAINT FK_F6E539FA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');

        // 6. Create trip_data table with TimescaleDB hypertable
        $this->addSql('CREATE SEQUENCE trip_data_id_seq START 1');
        $this->addSql('CREATE TABLE trip_data (
            id INT NOT NULL DEFAULT nextval(\'trip_data_id_seq\'),
            timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            trip_id INT NOT NULL,
            pid_name VARCHAR(50) NOT NULL,
            value NUMERIC(10, 4) DEFAULT NULL,
            unit VARCHAR(20) DEFAULT NULL,
            PRIMARY KEY (id, timestamp)
        )');
        $this->addSql('CREATE INDEX idx_trip_timestamp ON trip_data (trip_id, timestamp DESC)');
        $this->addSql('CREATE INDEX idx_pid_timestamp ON trip_data (pid_name, timestamp DESC)');
        $this->addSql('ALTER TABLE trip_data ADD CONSTRAINT FK_86CB6008A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');

        // 7. Convert to TimescaleDB hypertable (7-day chunks)
        $this->addSql("
            SELECT create_hypertable(
                'trip_data',
                'timestamp',
                chunk_time_interval => INTERVAL '7 days',
                if_not_exists => TRUE
            )
        ");

        // 8. Enable compression (segment by trip_id for better compression)
        $this->addSql("
            ALTER TABLE trip_data SET (
                timescaledb.compress,
                timescaledb.compress_segmentby = 'trip_id'
            )
        ");

        // 9. Add compression policy (compress after 7 days)
        $this->addSql("
            SELECT add_compression_policy(
                'trip_data',
                INTERVAL '7 days',
                if_not_exists => TRUE
            )
        ");

        // 10. Add retention policy (drop after 1 year)
        $this->addSql("
            SELECT add_retention_policy(
                'trip_data',
                INTERVAL '1 year',
                if_not_exists => TRUE
            )
        ");

        // 11. Insert Toyota Prius+ fixture
        $this->addSql("
            INSERT INTO vehicle_model (
                manufacturer,
                model,
                year_start,
                year_end,
                generation,
                engine_code,
                displacement,
                fuel_type,
                horse_power,
                electric_motor_power,
                is_hybrid,
                supported_pids,
                specifications
            ) VALUES (
                'Toyota',
                'Prius+',
                2012,
                2021,
                'XW40',
                '2ZR-FXE',
                1.8,
                'Hybrid Petrol',
                99,
                82,
                true,
                '{\"engine\": [\"01 05\", \"01 0C\", \"01 0D\", \"01 11\", \"01 21\"], \"fuel\": [\"01 03\", \"01 06\", \"01 07\", \"01 09\"], \"o2_sensors\": [\"01 14\", \"01 15\", \"01 24\", \"01 25\"], \"dtc\": [\"03\"]}',
                '{\"fuel_tank\": 45, \"curb_weight\": 1525, \"battery_voltage\": 201.6, \"battery_capacity\": 0.75}'
            )
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS trip_diagnostic CASCADE');
        $this->addSql('DROP TABLE IF EXISTS trip_data CASCADE');
        $this->addSql('DROP TABLE IF EXISTS trip CASCADE');
        $this->addSql('DROP TABLE IF EXISTS vehicle CASCADE');
        $this->addSql('DROP TABLE IF EXISTS vehicle_model CASCADE');
        $this->addSql('DROP TABLE IF EXISTS "user" CASCADE');
        $this->addSql('DROP SEQUENCE IF EXISTS trip_data_id_seq CASCADE');
    }
}
