<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251023151523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new CheckEngine database schema with User, Vehicle, LogSession, DataPoint entities and add Toyota Prius+ fixture';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE vehicles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE trips_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE trip_data_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE trip_metrics_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE analysis_history_id_seq CASCADE');
        $this->addSql('CREATE TABLE data_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pid_name VARCHAR(50) NOT NULL, value NUMERIC(10, 4) DEFAULT NULL, unit VARCHAR(20) DEFAULT NULL, log_session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F91A3FBB6B294064 ON data_point (log_session_id)');
        $this->addSql('CREATE INDEX idx_timestamp ON data_point (timestamp)');
        $this->addSql('CREATE INDEX idx_pid_name ON data_point (pid_name)');
        $this->addSql('CREATE TABLE log_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, file_path VARCHAR(255) DEFAULT NULL, session_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration INT DEFAULT NULL, distance NUMERIC(8, 2) DEFAULT NULL, data_points_count INT DEFAULT NULL, status VARCHAR(20) NOT NULL, analysis_results JSON DEFAULT NULL, catalyst_efficiency NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_st NUMERIC(5, 2) DEFAULT NULL, avg_fuel_trim_lt NUMERIC(5, 2) DEFAULT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E889ED43545317D1 ON log_session (vehicle_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nickname VARCHAR(100) NOT NULL, vin VARCHAR(17) DEFAULT NULL, license_plate VARCHAR(20) DEFAULT NULL, year SMALLINT NOT NULL, mileage INT DEFAULT NULL, purchase_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B80E4867E3C61F9 ON vehicle (owner_id)');
        $this->addSql('CREATE INDEX IDX_1B80E4867975B7E7 ON vehicle (model_id)');
        $this->addSql('CREATE TABLE vehicle_model (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, manufacturer VARCHAR(50) NOT NULL, model VARCHAR(100) NOT NULL, year_start SMALLINT NOT NULL, year_end SMALLINT DEFAULT NULL, generation VARCHAR(50) NOT NULL, engine_code VARCHAR(20) NOT NULL, displacement NUMERIC(3, 1) NOT NULL, fuel_type VARCHAR(50) NOT NULL, horse_power SMALLINT NOT NULL, electric_motor_power SMALLINT DEFAULT NULL, is_hybrid BOOLEAN NOT NULL, supported_pids JSON DEFAULT NULL, specifications JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE data_point ADD CONSTRAINT FK_F91A3FBB6B294064 FOREIGN KEY (log_session_id) REFERENCES log_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_session ADD CONSTRAINT FK_E889ED43545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4867E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4867975B7E7 FOREIGN KEY (model_id) REFERENCES vehicle_model (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_history DROP CONSTRAINT analysis_history_trip_id_fkey');
        $this->addSql('ALTER TABLE trip_data DROP CONSTRAINT trip_data_trip_id_fkey');
        $this->addSql('ALTER TABLE trip_metrics DROP CONSTRAINT trip_metrics_trip_id_fkey');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT trips_vehicle_id_fkey');
        $this->addSql('DROP TABLE analysis_history');
        $this->addSql('DROP TABLE trip_data');
        $this->addSql('DROP TABLE trip_metrics');
        $this->addSql('DROP TABLE trips');
        $this->addSql('DROP TABLE vehicles');

        // Insert Toyota Prius+ fixture
        $this->addSql("
            INSERT INTO vehicle_model (
                manufacturer,
                model,
                year_start,
                year_end,
                generation,
                engine_code,
                displacement,
                fuel_type,
                horse_power,
                electric_motor_power,
                is_hybrid,
                supported_pids,
                specifications
            ) VALUES (
                'Toyota',
                'Prius+',
                2012,
                2021,
                'XW40',
                '2ZR-FXE',
                1.8,
                'Hybrid Petrol',
                99,
                82,
                true,
                '[
                    \"010C\",
                    \"010D\",
                    \"0105\",
                    \"0106\",
                    \"0107\",
                    \"0124\",
                    \"0125\",
                    \"0134\",
                    \"0135\",
                    \"0146\",
                    \"0147\"
                ]'::json,
                '{
                    \"battery_capacity\": \"4.4 kWh\",
                    \"battery_type\": \"Nickel-Metal Hydride (NiMH)\",
                    \"fuel_tank\": \"45L\",
                    \"consumption_combined\": \"4.1L/100km\",
                    \"consumption_city\": \"3.9L/100km\",
                    \"consumption_highway\": \"4.4L/100km\",
                    \"co2_emissions\": \"96g/km\",
                    \"seats\": 7,
                    \"drivetrain\": \"FWD\",
                    \"transmission\": \"E-CVT\",
                    \"weight_kg\": 1525,
                    \"max_speed_kmh\": 165,
                    \"acceleration_0_100\": \"11.3s\",
                    \"catalyst_type\": \"Three-way catalytic converter\",
                    \"o2_sensors\": {
                        \"bank1_sensor1\": \"upstream\",
                        \"bank1_sensor2\": \"downstream\"
                    }
                }'::json
            )
        ");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE vehicles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE trips_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE trip_data_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE trip_metrics_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE analysis_history_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE analysis_history (id INT DEFAULT nextval(\'analysis_history_id_seq\'::regclass) NOT NULL, trip_id INT DEFAULT NULL, analysis_version VARCHAR(20) DEFAULT NULL, catalyst_efficiency DOUBLE PRECISION DEFAULT NULL, health_score INT DEFAULT NULL, efficiency_delta DOUBLE PRECISION DEFAULT NULL, health_score_delta INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D6B164DA5BC2E0E ON analysis_history (trip_id)');
        $this->addSql('CREATE TABLE trip_data (id BIGINT DEFAULT nextval(\'trip_data_id_seq\'::regclass) NOT NULL, trip_id INT DEFAULT NULL, "timestamp" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, time_seconds DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, gps_speed_ms DOUBLE PRECISION DEFAULT NULL, o2_b1s1_voltage DOUBLE PRECISION DEFAULT NULL, o2_b1s2_voltage DOUBLE PRECISION DEFAULT NULL, o2_b1s1_wide_range DOUBLE PRECISION DEFAULT NULL, o2_b1s1_lambda DOUBLE PRECISION DEFAULT NULL, stft DOUBLE PRECISION DEFAULT NULL, ltft DOUBLE PRECISION DEFAULT NULL, afr_measured DOUBLE PRECISION DEFAULT NULL, afr_commanded DOUBLE PRECISION DEFAULT NULL, cat_temp_1 DOUBLE PRECISION DEFAULT NULL, cat_temp_2 DOUBLE PRECISION DEFAULT NULL, coolant_temp DOUBLE PRECISION DEFAULT NULL, intake_temp DOUBLE PRECISION DEFAULT NULL, rpm INT DEFAULT NULL, engine_load DOUBLE PRECISION DEFAULT NULL, maf DOUBLE PRECISION DEFAULT NULL, speed_kmh DOUBLE PRECISION DEFAULT NULL, prius_af_lambda DOUBLE PRECISION DEFAULT NULL, prius_afs_voltage DOUBLE PRECISION DEFAULT NULL, prius_engine_speed DOUBLE PRECISION DEFAULT NULL, engine_running BOOLEAN DEFAULT false, engine_warm BOOLEAN DEFAULT false, analyzable BOOLEAN DEFAULT false, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_trip_data_trip_id ON trip_data (trip_id)');
        $this->addSql('CREATE INDEX idx_trip_data_timestamp ON trip_data ("timestamp")');
        $this->addSql('CREATE INDEX idx_trip_data_analyzable ON trip_data (analyzable) WHERE (analyzable = true)');
        $this->addSql('CREATE TABLE trip_metrics (id INT DEFAULT nextval(\'trip_metrics_id_seq\'::regclass) NOT NULL, trip_id INT DEFAULT NULL, metric_name VARCHAR(100) NOT NULL, metric_value DOUBLE PRECISION NOT NULL, metric_unit VARCHAR(20) DEFAULT NULL, metric_category VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_trip_metrics_trip_id ON trip_metrics (trip_id)');
        $this->addSql('CREATE INDEX idx_trip_metrics_name ON trip_metrics (metric_name)');
        $this->addSql('CREATE INDEX idx_trip_metrics_category ON trip_metrics (metric_category)');
        $this->addSql('CREATE TABLE trips (id INT DEFAULT nextval(\'trips_id_seq\'::regclass) NOT NULL, vehicle_id INT DEFAULT NULL, filename VARCHAR(255) NOT NULL, file_hash VARCHAR(64) DEFAULT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', trip_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_seconds INT DEFAULT NULL, distance_km DOUBLE PRECISION DEFAULT NULL, trip_type VARCHAR DEFAULT \'unknown\', catalyst_efficiency DOUBLE PRECISION DEFAULT NULL, health_score INT DEFAULT NULL, o2_amont_avg DOUBLE PRECISION DEFAULT NULL, o2_amont_std DOUBLE PRECISION DEFAULT NULL, o2_aval_avg DOUBLE PRECISION DEFAULT NULL, o2_aval_std DOUBLE PRECISION DEFAULT NULL, stft_avg DOUBLE PRECISION DEFAULT NULL, stft_min DOUBLE PRECISION DEFAULT NULL, stft_max DOUBLE PRECISION DEFAULT NULL, ltft_avg DOUBLE PRECISION DEFAULT NULL, ltft_min DOUBLE PRECISION DEFAULT NULL, ltft_max DOUBLE PRECISION DEFAULT NULL, cat_temp_avg DOUBLE PRECISION DEFAULT NULL, cat_temp_max DOUBLE PRECISION DEFAULT NULL, coolant_temp_avg DOUBLE PRECISION DEFAULT NULL, rpm_avg DOUBLE PRECISION DEFAULT NULL, engine_load_avg DOUBLE PRECISION DEFAULT NULL, maf_avg DOUBLE PRECISION DEFAULT NULL, analyzable_samples INT DEFAULT NULL, total_samples INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_trips_uploaded_at ON trips (uploaded_at)');
        $this->addSql('CREATE UNIQUE INDEX trips_file_hash_key ON trips (file_hash)');
        $this->addSql('CREATE INDEX idx_trips_vehicle_id ON trips (vehicle_id)');
        $this->addSql('CREATE INDEX idx_trips_trip_date ON trips (trip_date)');
        $this->addSql('CREATE INDEX idx_trips_catalyst_efficiency ON trips (catalyst_efficiency)');
        $this->addSql('CREATE INDEX idx_trips_health_score ON trips (health_score)');
        $this->addSql('CREATE TABLE vehicles (id INT DEFAULT nextval(\'vehicles_id_seq\'::regclass) NOT NULL, name VARCHAR(100) NOT NULL, model VARCHAR(100) DEFAULT \'Prius+\', year INT DEFAULT NULL, mileage_km INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\', PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE analysis_history ADD CONSTRAINT analysis_history_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_data ADD CONSTRAINT trip_data_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trip_metrics ADD CONSTRAINT trip_metrics_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT trips_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE data_point DROP CONSTRAINT FK_F91A3FBB6B294064');
        $this->addSql('ALTER TABLE log_session DROP CONSTRAINT FK_E889ED43545317D1');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4867E3C61F9');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4867975B7E7');
        $this->addSql('DROP TABLE data_point');
        $this->addSql('DROP TABLE log_session');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE vehicle_model');
    }
}
