<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251024034003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE obd2_column (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, category VARCHAR(50) NOT NULL, unit VARCHAR(20) DEFAULT NULL, data_type VARCHAR(20) NOT NULL, min_value DOUBLE PRECISION DEFAULT NULL, max_value DOUBLE PRECISION DEFAULT NULL, error_values JSON DEFAULT NULL, validation_criteria JSON DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2D23C745E237E06 ON obd2_column (name)');
        $this->addSql('CREATE TABLE obd2_column_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, variant_name VARCHAR(255) NOT NULL, priority INT NOT NULL, source VARCHAR(50) NOT NULL, active BOOLEAN NOT NULL, column_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97C37F4EBE8E8ED5 ON obd2_column_variant (column_id)');
        $this->addSql('CREATE INDEX idx_variant_name ON obd2_column_variant (variant_name)');
        $this->addSql('ALTER TABLE obd2_column_variant ADD CONSTRAINT FK_97C37F4EBE8E8ED5 FOREIGN KEY (column_id) REFERENCES obd2_column (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_trip_data_timestamp RENAME TO idx_timestamp');
        $this->addSql('ALTER INDEX idx_trip_data_pid_name RENAME TO idx_pid_name');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE obd2_column_variant DROP CONSTRAINT FK_97C37F4EBE8E8ED5');
        $this->addSql('DROP TABLE obd2_column');
        $this->addSql('DROP TABLE obd2_column_variant');
        $this->addSql('ALTER INDEX idx_pid_name RENAME TO idx_trip_data_pid_name');
        $this->addSql('ALTER INDEX idx_timestamp RENAME TO idx_trip_data_timestamp');
    }
}
