version: 2

updates:
  # Composer dependencies (Backend Symfony)
  - package-ecosystem: "composer"
    directory: "/backend-symfony"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "composer"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "backend"
    groups:
      symfony:
        patterns:
          - "symfony/*"
      doctrine:
        patterns:
          - "doctrine/*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Python dependencies (Backend Python)
  - package-ecosystem: "pip"
    directory: "/backend-python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "pip"
    labels:
      - "dependencies"
      - "python"
      - "backend"

  # NPM dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    groups:
      vue:
        patterns:
          - "vue*"
          - "@vue/*"
      dev-dependencies:
        dependency-type: "development"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/docker/symfony"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "gregzter"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
