parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Services publics pour scripts CLI et démo
    App\Service\OBD2ColumnMapper:
        public: true
    
    App\Service\DiagnosticDetector:
        public: true
