parameters:
    upload_dir: '%kernel.project_dir%/var/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Bind upload directory parameter
    App\Controller\Api\TripController:
        bind:
            $uploadDir: '%upload_dir%'

    # Services publics pour scripts CLI et démo
    App\Service\OBD2ColumnMapper:
        public: true

    App\Service\DiagnosticDetector:
        public: true

    App\Service\OBD2CsvParser:
        public: true

    App\Service\TripDataService:
        public: true

    App\Service\Diagnostic\StreamingDiagnosticAnalyzer:
        public: true

    # Validator public pour tests CLI
    Symfony\Component\Validator\Validator\ValidatorInterface:
        alias: 'validator'
        public: true
