framework:
    router:
        strict_requirements: null
    profiler:
        only_exceptions: false
        collect_serializer_data: true

web_profiler:
    toolbar: true
    intercept_redirects: false
